### ISSUE TITLE
Option to pre-load a string to query

### ISSUE THREAD

**Issue by gauthierc** [autobib/nucleo-picker#7]
Hello,
Thank you for this tool, which makes nucleo easy to use.
I want to migrate from skim to nucleo and I'm missing an option.
In skim I can specify a query that pre-feeds the search with a string.
https://docs.rs/skim/0.10.4/skim/prelude/struct.SkimOptionsBuilder.html#method.query
Is it possible to do the same with nucleo and nucleo-picker?
Thanks

**Comment by alexrutar** [comment]
Thanks for the suggestion! This isn't currently possible but should be easy to implement; I've been planning to set up more general configuration options for the `Picker` in any case (e.g. to also fix #2) and I'll implement this at the same time. It will be a breaking change but should be in `v0.5.0`.
